[package]
name = "oxideav-wavpack"
version = "0.0.2"
edition = "2021"
rust-version = "1.80"
license = "MIT"
repository = "https://github.com/OxideAV/oxideav-wavpack"
authors = ["Mark Karpeles"]
description = "Pure-Rust WavPack lossless audio decoder for the oxideav framework"

readme = "README.md"
homepage = "https://github.com/OxideAV/oxideav-wavpack"
keywords = ["multimedia", "audio", "wavpack", "lossless", "pure-rust"]
categories = ["multimedia::encoding", "multimedia::audio"]

[dependencies]
oxideav-core = "0.1"
